# Generated by Django 4.1.7 on 2023-04-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_gmao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['type_contract', 'name'], 'verbose_name_plural': 'persons'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='prenom_person',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='residance',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='type_persons',
            new_name='type_contract',
        ),
        migrations.AlterField(
            model_name='person',
            name='nom_societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societes', related_query_name='societe', to='mtb_gmao.societe'),
        ),
    ]
