# Generated by Django 4.1.7 on 2023-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_gmao', '0002_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='societe',
            name='imatriculation',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
