# Generated by Django 4.1.7 on 2023-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_gmao', '0003_alter_person_phone_alter_societe_imatriculation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
