# Generated by Django 4.1.7 on 2023-04-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_gmao', '0004_alter_societe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='societe',
            old_name='siège_social',
            new_name='siege_social',
        ),
        migrations.AlterField(
            model_name='person',
            name='residence',
            field=models.CharField(max_length=80),
        ),
    ]
