# Generated by Django 4.1.7 on 2023-04-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_gmao', '0005_rename_siège_social_societe_siege_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type_contract',
            field=models.CharField(choices=[('cdd', 'CDD'), ('cdi', 'CDI'), ('partiel', 'INTERIME'), ('None', 'END_CONTRAT')], help_text='choose type of contrat', max_length=8),
        ),
        migrations.AlterField(
            model_name='societe',
            name='type_societe',
            field=models.CharField(choices=[('my_societe', 'Societe'), ('fournisseur', 'Fournisseur'), ('prestataire', 'Prestataire'), ('ONG', 'Donnateur'), ('None', 'END_CONTRAT')], help_text='choose if your are personne or company', max_length=13),
        ),
    ]
